<?php

/**
*
* Artiste
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Artiste extends Entity {
    public $nom;     // varchar(255)
    public $nbTab;     // int

    public function __construct(
        $nom = "",
        $nbTab = "",
    $id = false) {
        parent::__construct($id);

        $this->nom = $nom;
        $this->nbTab = $nbTab;
    }
}
?>
