<?php

/**
*
* Instrument
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Instrument extends Entity {
    public $type;     // varchar

    public function __construct(
        $type = "",
    $id = false) {
        parent::__construct($id);

        $this->type = $type;
    }
}
?>
