<?php

/**
*
* Tab
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Tab extends Entity {
    public $titre;     // varchar(255)
    public $album;     // varchar(255)
    public $cheminTab;     // varchar(255)
    public $dateAjout;     // varchar(255)
    public $Artiste;     // varchar(255)
    public $Genre;     // varchar(255)
    public $Instrument;     // varchar(255)

    public function __construct(
        $titre = "",
        $album = "",
        $cheminTab = "",
        $dateAjout = "",
        $Artiste = "",
        $Genre = "",
        $Instrument = "",
    $id = false) {
        parent::__construct($id);

        $this->titre = $titre;
        $this->album = $album;
        $this->cheminTab = $cheminTab;
        $this->dateAjout = $dateAjout;
        $this->Artiste = $Artiste;
        $this->Genre = $Genre;
        $this->Instrument = $Instrument;
    }
}
?>
