<?php

/* queries.twig */
class __TwigTemplate_c6d7c92664e7bd4d8dde1361d132b4b8f2682caa78d53e3b0cef41dc3f85c134 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 2
        echo "<?php

/**
*
* ";
        // line 6
        echo (isset($context["tableName"]) ? $context["tableName"] : $this->getContext($context, "tableName"));
        echo "
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\\Models\\Queries;

use Helpers\\DB\\Query;

class  ";
        // line 16
        echo (isset($context["tableName"]) ? $context["tableName"] : $this->getContext($context, "tableName"));
        echo " extends Query {
}
?>
";
    }

    public function getTemplateName()
    {
        return "queries.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  38 => 16,  25 => 6,  19 => 2,);
    }
}
/* {% autoescape false %}*/
/* <?php*/
/* */
/* /***/
/* **/
/* * {{ tableName }}*/
/* **/
/* * This class was generated by a script. Please be careful changing it.*/
/* * Regenerate it will erase all changes!*/
/* *//* */
/* */
/* namespace App\Models\Queries;*/
/* */
/* use Helpers\DB\Query;*/
/* */
/* class  {{ tableName }} extends Query {*/
/* }*/
/* ?>*/
/* {% endautoescape %}*/
