user:
  login: varchar(255)
  email: varchar(255)
  password: varchar(255)
  cookie: varchar(255)

tablature:
  titre: varchar(255)
  album: varchar(255)
  cheminTab: varchar(255)
  dateAjout: datetime
  idArtiste: int
  idGenre: int
  idInstrument: int

genre:
  nom: varchar(255)

artiste:
  nom: varchar(255)
  nbTab: int

instrument:
  type: varchar(255)