user:
  login: varchar(255)
  email: varchar(255)
  password: varchar(255)
  cookie: varchar(255)
  admin: bool

tab:
  titre: varchar(255)
  album: varchar(255)
  cheminTab: varchar(255)
  dateAjout: varchar(255)
  Artiste: varchar(255)
  Genre: varchar(255)
  Instrument: varchar(255)

genre:
  nom: varchar(255)

artiste:
  nom: varchar(255)
  nbTab: int

instrument:
  type: varchar(255)